import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
    
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '../Images/1.jpg',
        regularPrice: 120,
        offerPrice:60,
        discountPercentage:30,
        brand: 'Nike',
        countInStock:5,
        rating: 4.5,
        size:'60 gm',
        numReviews: 10,
        description: 'high quality product',
      },
      {
     
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        offerPrice:50,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        countInStock:5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
   
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '../Images/12.jpg',
        regularPrice: 220,
        offerPrice:170,
        discountPercentage:40,
        brand: 'Lacoste',
        rating: 4.8,
        countInStock:5,
        numReviews: 17,
        size:'80 gm',
        description: 'high quality product',
      },
      {
      
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '../Images/10.jpg',
        regularPrice: 78,
        offerPrice:56,
        countInStock:5,
        discountPercentage:40,
        size:'100 gm' ,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {

        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
    
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
     
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
    
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
    
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60',
       
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
     
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 ',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
   
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 ',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
      
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 ',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
       
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
      
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:50,
        size:'60 ',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
    
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '../Images/7.jpg',
        regularPrice: 100,
        countInStock:5,
        offerPrice:6,
        size:'60 gm',
        discountPercentage:50,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
   
     

  
    ],
  };
  export default data;